GET http://localhost:8080/api/courier
Accept: application/json

###
GET http://localhost:8080/api/courier/4
Accept: application/json

###
POST http://localhost:8080/api/courier
Content-Type: application/json

{
  "lastName": "Lakatos",
  "firstName": "Lacika",
  "mobileNumber": "+36703456782",
  "creatorID": 6,
  "modifierID": 6
}
###
PUT http://localhost:8080/api/courier
Content-Type: application/json

{
  "id": 5,
  "lastName": "Lakatos",
  "firstName": "Laszlo",
  "mobileNumber": "+36703456747",
  "creatorID": 6,
  "modifierID": 6
}
###

DELETE http://localhost:8080/api/courier/8
Accept: application/json

###