GET http://localhost:8080/api/order
Accept: application/json

###
GET http://localhost:8080/api/order/21
Accept: application/json

###
POST http://localhost:8080/api/order
Content-Type: application/json

{
  "city": "Budapest",
  "street": "Asztória",
  "typeOfStreet": "Utca",
  "houseNumber": "47",
  "furnitureList": "1;2;9",
  "courierID": null,
  "creatorID": 13,
  "modifierID": 6
}
###

PUT http://localhost:8080/api/order
Content-Type: application/json

{
  "id": 23,
  "city": "Budapest",
  "street": "Asztóriaa",
  "typeOfStreet": "Utca",
  "houseNumber": "47",
  "furnitureList": "1;2;9",
  "courierID": null,
  "creatorID": 13,
  "modifierID": 6
}
###
DELETE http://localhost:8080/api/order/23
Accept: application/json
